Вторая задача. Проведена декомпощиция программы на составные элементы…
DavidGelmanSerg/JavaLearn pull request #2
Opened 2024-02-25 06:01 UTC by DavidGelmanSerg

…, Добавлена возможность вывода в файл, получения выражения и имени файла из аргументов командной строки. Добавлена возможность расширения набора операций. Добавлена валидация входного выражения.

2024-03-04 06:23 UTC, Yuksovich requested changes

2024-03-04 06:23 UTC, Yuksovich commented on SimpleCalculator/SimpleCalculator.iml
> +<?xml version="1.0" encoding="UTF-8"?>
всю папку .idea со всем содержимым надо исключить из репозитория и добавить в .gitignore

2024-03-04 06:23 UTC, Yuksovich commented on SimpleCalculator/src/Calculator.java
> +        expression = _expression.replace(" ", "");
нижнее подчеркивание не используется в именовании переменных и параметров в джаве обычно. В данном случае делают `this.expression = expression.replace...`

2024-03-04 06:23 UTC, Yuksovich commented on SimpleCalculator/src/InputParser.java
> +    private final String[] Options;
с большой буквы не именуются переменные, поля, методы в джаве

2024-03-04 06:23 UTC, Yuksovich commented on SimpleCalculator/src/InputParser.java
> +        Options = options;
`this.options = options` this ключевое слово, для ссылки на текущий объект. Такой конструктор может автоматом генерировать IDEA

2024-03-04 06:23 UTC, Yuksovich commented on SimpleCalculator/src/Calculator.java
> +    public Calculator() {
зачем тут пустой конструктор?

2024-03-04 06:23 UTC, Yuksovich commented on SimpleCalculator/src/Calculator.java
> +        if (newExpression.matches("-?\\d+(\\.\\d+)?[-+*/:]-?\\d+(\\.\\d+)?") || newExpression.matches(("-?\\d+(\\.\\d+)?")))
во-первых, это логика явно парсера. Во-вторых - достаточно тяжело понять, что тут за регекспы, они в целом плохо читаются. 
Так же, не стоит делать "магические константы" подобные регекспы и константные строки выносят в private static final поле с говорящим названием. Констнтные поля именуют в UPPER_SNAKE_CASE

2024-03-04 06:23 UTC, Yuksovich commented on SimpleCalculator/src/Calculator.java
> +            expression = newExpression;
возможно для парсинга стоит попробовать класс Scanner

2024-03-04 06:23 UTC, Yuksovich commented on SimpleCalculator/src/InputParser.java
> +            if (Options[i].equals(key) && isValue(i + 1)) {
чтобы каждый раз не перебирать значения при обращении лучше сразу все сложить в Map и доставать по ключу

2024-03-04 06:23 UTC, Yuksovich commented on SimpleCalculator/src/InputParser.java
> +    private boolean isValue(int keyIndex) {
похоже тут правильнее hasValue

2024-03-04 06:23 UTC, Yuksovich commented on SimpleCalculator/src/operations/Division.java
> +    public double compute(double[] args) {
вообще у double очень специфическая точность, поскольку в двоичном представлении нельзя точно представить десятичное дробное число. Поэтому для точных вычислений, особенно когда дело касается финансов double никогда не используют.
Для примера можешь попробовать, что выведет выражение:
```java
        double sum = 1.03 + 0.67;
        System.out.println("sum = " + sum);
```
 
поэтому обычно используется BigDecimal

2024-03-04 06:23 UTC, Yuksovich commented on SimpleCalculator/src/operations/Operation.java
> +    public Operation() {
пустой конструктор всегда генерируется автоматом, если другой отсутствует, поэтому его не надо писать

2024-03-04 06:23 UTC, Yuksovich commented on SimpleCalculator/src/operations/Multiplication.java
> +    public double compute(double[] args) {
если операции всегда работают с двумя аргументами - то почему бы им на вход и не принмать 2 аргумента? тут не возникнет проблем с типизацией и выходами за пределы массива, если появится например оператор, работающий с одним числом. Массивов вообще обычно стараются избегать, потому как это более низкоуровневая вещь, чем объекты в ООП. С ними неудобно работать.

2024-03-04 06:23 UTC, Yuksovich commented on SimpleCalculator/src/operations/Multiplication.java
> +public class Multiplication extends Operation {
Вообще в пакете java.util.function есть уже подобные штуки, чтобы не создавать подобные интерфейсы, вроде Operation. В данном случае BinaryOperator<T> посмотри, заодно познакомишься с дженериками

2024-03-04 06:23 UTC, Yuksovich commented on SimpleCalculator/src/operations/Operation.java
> +            default -> new Division();
не надо в default ветку класть какую-то логику, подходящую под определенный кейс. Если у тебя появится новый оператор, например возведение в степень - это сразу сломается, а ты и не заметишь сразу. 
Для деления делается такая же ветка case, а вот в дефолте обычно кидается исключение, напрмер UnsupportedOperationException в которой пишешь, что такая операция не поддерживается и сразу в текст можно вписать какая операция. Так, ты сразу увидешь ошибку и откуда она пришла, при добавлении нового функционала

2024-03-04 06:23 UTC, Yuksovich commented on SimpleCalculator/src/Main.java
> +        } catch (FileNotFoundException e) {
во-первых логика на экспешенах - это не правильно. 
Если файла нет, то он вообще должен быть создан, что логично, так обычно программы делают.
Во-вторых, если файл не указан и только тогда программа должна писать в консоль, а не если не получилось в файл, при этом просто проглатывая исключение.
Зачастую такие программы используют в скриптах, которые делают последовательные операции и используют результат одних как входные данные других операций, в данном случае программа успешно отработает, якобы, но по факту не сделает, что от нее требуется

2024-03-04 06:23 UTC, Yuksovich commented on SimpleCalculator/src/Main.java
> +            System.exit(0);
если ошибка, то почему 0? 0 это успешное завершение программы, в данном случае программа явно завершается с ошибкой

2024-03-04 06:23 UTC, Yuksovich commented on SimpleCalculator/src/Calculator.java
> +            Operation operation = Operation.getOperation(expression.split("-?\\d+(\\.\\d+)?")[1]);
это тоже логика парсера, калькулятор должен считать

2024-03-04 06:23 UTC, Yuksovich commented on SimpleCalculator/src/Calculator.java
> +            Pattern pattern = Pattern.compile("-?\\d+");
скомпилированный паттерн лучше в константу, чтобы посчитать его только раз, регекспы компилить относительно дорого

2024-03-04 06:23 UTC, Yuksovich commented on SimpleCalculator/src/Main.java
> +public class Main {
хотелось бы увидеть более четкие и понятные разбиения на абстракции.
Т.е. каждая абстракция должна быть понятной и должна выполнять ровно одну функцию и только ту, которая следуют из ее названия.
Т.е. если у тебя есть Parser - парсер парсит, он должен преобразовывать строку в набор параметров, удобных для дальнейшего использования, неважно откуда и как их получили.
Калькулятор - слишком общее понятие возможно, потому как это множество функций и по сути они являются сутью программы. Поэтому тут должно что-то считать, что-то парсить, что-то выводить.
Мэин класс по сути является модератором - т.е. он управляет ходом выполнения программы и должен быть максимально простым и общим, т.е. создать нужные объекты, получть от одного, передать другому, обработать ошибки.  Если я тебе скажу, что теперь в задании надо читать выражение из файла или парсить с веб ресурса - у тебя будут появляться новые и новые ветви if-else в мэине - он будет расти, это будет сильно усложнять его чтение, так же может сломать уже существующую логику. Есть принцип открытости/закрытости из SOLID советую ознакомится с ним, как и с остальными принципами.

2024-03-04 06:23 UTC, Yuksovich commented on SimpleCalculator/src/Main.java
> +public class Main {
такие штуки придут со временем, не сразу понятно, как это правильнее сделать, но надо к этому стремиться, что мы попытаемся сделать.

2024-03-04 06:23 UTC, Yuksovich commented on SimpleCalculator/src/Calculator.java
> +        else
всегда в ветках if и else используй фигурные скобки.
Да, язык позволяет этого не делать, если строка всего одна, но так делать не стоит. Если потом кто-то добавит строку то программа будет работать неправильно, а ты даже не заметишь

2024-03-04 06:23 UTC, Yuksovich commented on SimpleCalculator/src/Calculator.java
> +            throw new ExpressionNotValidException("Выражение введено неверно. Попробуйте ввести его в формате: число [-+*/:] число");
мы абстрагируемся от того, что кто-то как-то нам передает число. В данном случае мы просто обрабатываем строку, поэтому и исключение должно быть максимально абстрактным и не обращаться к контексту программы, тогда это можно будет переиспользовать.
Исключения выбрасываются зачастую из глубины программы и вообще не известно заранее откуда и куда оно прилетит. Поэтому они обычно содержат какие-то сообщения для отладки, а уж та часть программы, которая взаимодействует с пользователем делает обработку исключения и превращает его в сообщение.
Представь, что программа растет развивается и калькулятор стал каким-то куском логики большого веб приложения. Пользователь заходит на сайт, открывает личный кабинет, а у него там вместо баланса 
"Выражение введено неверно. Попробуйте ввести его в формате: число [-+*/:] число". И он думает, какое число? я же ничего не вводил, просто сайт открыл? 
Поэтому каждый объект выполняет действия на том уровне абстракции, на котором он находится, тогда такие объекты потом можно переиспользовать и легко расширять

2024-04-01 08:40 UTC, Yuksovich commented on SimpleCalculator/src/output/streams/IStream.java
> +public interface IStream {
во-первых `I` в именах интерфейсов в джава не принято использовать, не канонично это, так сказать. Так принято в C#. 
Во-вторых, что более существенно это непонятная абстракция. Что такое Stream? В джава есть стримы для ввода/вывода типа InputStream и OutputStream, а так же есть Stream API, для обработки данных в функциональном стиле. К этом мы придем позже. Так или иначе, что такое IStream - не понятно. Что он должен делать - вывод или ввод. Затем у тебя тут есть метод print - который просто печатает число, и это явно находится на другом уровне абстракции, чем Stream. Для примера, это как если бы ты сделал колесо, у которого есть метод "повернуть автомобиль". Но колесо не обязательно на автомобиле, оно не обязательно переднее и связано с рулем. Да и по сути колесо только крутится, оно не отвечает за поворот автомобиля, за это отвечает рулевые тяги, которые поворачивают колесо.
Следующая проблема этого метода то, что он принимает double. Double это только число, при этом если мы хотим, чтобы вывод был "Ответ: 42" этот интерфейс уже не подойдет. Поэтому строка более универсальный аргумент, поскольку все что отображается может быть строкой и все данные можно представить в виде строки. Для этого, кстати, в джава даже часто используется интерфейс CharSequence - т.е. последовательность символов, который является абстракцией над строкой. Но в большинстве случаев используют просто строку

2024-04-01 08:40 UTC, Yuksovich commented on SimpleCalculator/src/output/streams/FileStream.java
> +            System.exit(0);
никогда не пиши метод System.exit нигде, кроме метода main. Потому как за ходом выполнения программы следит в данном случает метод main и то, что программа может завершить свою работу за его пределами может быть неожиданностью для всех. Например, ты захочешь поменять порядок вызовов классов, а программа внезапно выйдет. Это так же нарушение принципа единой ответственности и абстракции. Это класс для вывода в файл, он не должен ничего больше делать.
Но самое худшее, что может случится, если ты этот класс затащишь в серверное приложение. 99% программ на Java это серверные приложения, они запускаются и работают условно бесконечно. Если где-то возникает ошибка - она просто возвращается пользователю или куда-то логируется/записывается. А вот если ты случайно где-то позовешь System.exit - ты просто положишь сервер. Приложение просто закончит работу и все.

2024-04-01 08:40 UTC, Yuksovich commented on SimpleCalculator/src/output/streams/FileStream.java
> +            System.out.println("Файл, который вы указали, не существует!");
Про System.out вот так в явном виде - так же стоит забыть. Во-первых, у тебя может просто не быть консоли. Во-вторых, ты тут пишешь в файл, о какой консоли идет речь? тут не должно быть ее. Мы следующим шагом сделаем UI интерфейс и что ты будешь делать с консолью?
Обработка ошибок - так же не отоветственность данного класса, у тебя есть main - там обрабатываются ошибки. Это хорошая практика, когда есть единое место куда сваливаются все ошибки и обрабатываются там и там же решается куда их вывести и что с ними делать.

2024-04-01 08:40 UTC, Yuksovich commented on SimpleCalculator/src/output/Output.java
> +    private IStream outputStream;
если можно сделать поле final - лучше сделать его final. Стоит ли делать тут setOutputStream?

2024-04-01 08:40 UTC, Yuksovich commented on SimpleCalculator/src/output/Output.java
> +public class Output {
кажется, что этот класс в целом бессмысленный. Они ничего не делает, кроме как проксирует данные в IStream. Кажется как раз должен быть интерфейс OutputPrinter с методом print, и у него выбирается реализация в зависимости от агрумента командной строки. Это по сути и есть паттерн Стратегия

2024-04-01 08:40 UTC, Yuksovich commented on SimpleCalculator/src/input/parser/InputParser.java
> +    private Map<String, String> options = new HashMap<String, String>();
здесь тоже стоит сдеать final

2024-04-01 08:40 UTC, Yuksovich commented on SimpleCalculator/src/input/parser/InputParser.java
> +        while (i < args.length) {
цикл с инкрементируемым аргументом до достижения условия лучше использовать for
`for(int i = 0; i < args.length; i += 2) {...}`

2024-04-01 08:40 UTC, Yuksovich commented on SimpleCalculator/src/input/parser/InputParser.java
> +    public boolean isOption(String key) {
тут лучше hasOption

2024-04-01 08:40 UTC, Yuksovich commented on SimpleCalculator/src/input/parser/InputParser.java
> +    public Operation getExpression() throws InvalidExpressionException {
а почему метод getExpression возвращает Operation? Вообще это не ответственность парсера создавать какие-то объекты

2024-04-01 08:40 UTC, Yuksovich commented on SimpleCalculator/src/input/parser/InputParser.java
> +            System.out.println("Введите выражение:");
как уже говорил - не должно быть System.out.print. Парсер парсит, не должен он ничего писать никуда. 
Принцип единой ответственности

2024-04-01 08:40 UTC, Yuksovich commented on SimpleCalculator/src/input/parser/InputParser.java
> +    public void printOptions() {
этого вообще не должно быть. Можно переопределить метод toString() и кому надо позовет его, чтобы вывести содержимое

2024-04-01 08:40 UTC, Yuksovich commented on SimpleCalculator/src/input/parser/InputParser.java
> +        return (value == null) ? "" : value;
советую внимательнее ознакомится с методами Map, например в данном случае есть метод `getOrDefault` который как раз делает то же самое, только в один метод.

2024-04-01 08:40 UTC, Yuksovich commented on SimpleCalculator/src/input/analyzer/exceptions/InvalidExpressionException.java
> +        super("");
в этом вообще нет смысла. Можно просто не делать конструктор, будет дефолтный без аргументов и все.

2024-04-01 08:40 UTC, Yuksovich commented on SimpleCalculator/src/input/analyzer/exceptions/InvalidExpressionException.java
> +public class InvalidExpressionException extends Exception{
Ты знаешь, какие исключения проверяемы, а какие нет? что вообще это такое? Очень важно знать и понимать иерархию исключений, потому как при собеседовании на первую работу у тебя это спросят с вероятностью 95%. 
В общем Exception проверяемое исключение и в целом их обычно использовать не удобно, потому как их надо прописывать в сигнатурах методов, и лучше использовать непроверяемые

2024-04-01 08:40 UTC, Yuksovich commented on SimpleCalculator/src/input/analyzer/Analyzer.java
> +public class Analyzer {
Анализатор, очень общее понятие, и по факту оно и парсер и валидатор. Опять таки не цельная абстракция без единой ответственности

2024-04-01 08:40 UTC, Yuksovich commented on SimpleCalculator/src/calculator/operations/Sum.java
> +    public void setOperand1(double operand) {
цифры в именах методов считают дурным тоном. За исключением того, что это кусок какой-то бизнес логики, например когда у тебя банк и есть какая-то форма 357 например и ты делаешь метод `getForm357()` иначе цифры не стоит использовать. Можно заменить setFirstOperand, setSecond... хотя тут вообще лучше использовать конструктор и final поля. Почитай про Immutable объекты и чем они хороши.
Вообще если выпадает свободная минутка, советую почитывать Джошуа Блох: Java. Эффективное программирование. (Joshua Bloch - Effective Java). Там много подобных нюансов описано

2024-04-01 08:40 UTC, Yuksovich commented on SimpleCalculator/src/calculator/operations/Operation.java
> +            default -> new Division();
про default в данном случае тоже уже писал в комментах ранее

2024-04-01 08:40 UTC, Yuksovich commented on SimpleCalculator/src/calculator/exceptions/DivisionByZeroException.java
> +    public DivisionByZeroException() {
в этом конструкторе нет нужды, он сгенерируется автоматом

2024-04-01 08:40 UTC, Yuksovich commented on SimpleCalculator/src/calculator/Calculator.java
> +    private Operation operation;
final

2024-04-01 08:40 UTC, Yuksovich commented on SimpleCalculator/src/Main.java
> +            System.out.println("Отсутствует значение для аргумента: " + invalidArg.getMessage());
то же самое про System.out. У тебя есть Output - пиши в него

2024-04-02 15:22 UTC, DavidGelmanSerg commented on SimpleCalculator/src/Calculator.java
> +        expression = _expression.replace(" ", "");
Сделано

2024-04-02 15:22 UTC, DavidGelmanSerg commented on SimpleCalculator/src/InputParser.java
> +    private final String[] Options;
Сделано

2024-04-02 15:23 UTC, DavidGelmanSerg commented on SimpleCalculator/src/Calculator.java
> +    public Calculator() {
сделано

2024-04-02 15:24 UTC, DavidGelmanSerg commented on SimpleCalculator/src/Calculator.java
> +            Operation operation = Operation.getOperation(expression.split("-?\\d+(\\.\\d+)?")[1]);
сделано

2024-04-02 15:25 UTC, DavidGelmanSerg commented on SimpleCalculator/src/Calculator.java
> +        else
сделано

2024-04-02 15:27 UTC, DavidGelmanSerg commented on SimpleCalculator/src/InputParser.java
> +            if (Options[i].equals(key) && isValue(i + 1)) {
сделано

2024-04-02 15:28 UTC, DavidGelmanSerg commented on SimpleCalculator/src/InputParser.java
> +    private boolean isValue(int keyIndex) {
в последнем коммите заменено на hasOption

2024-04-02 15:38 UTC, DavidGelmanSerg commented on SimpleCalculator/src/output/streams/FileStream.java
> +            System.exit(0);
Очень дельный и очевидный коммент. Я об этом не подумал, ибо думал только о конкретной задаче. исправил.

2024-04-02 15:40 UTC, DavidGelmanSerg commented on SimpleCalculator/src/input/parser/InputParser.java
> +    private Map<String, String> options = new HashMap<String, String>();
сделано

2024-04-02 15:40 UTC, DavidGelmanSerg commented on SimpleCalculator/src/input/parser/InputParser.java
> +        while (i < args.length) {
сделано

2024-04-02 15:40 UTC, DavidGelmanSerg commented on SimpleCalculator/src/input/parser/InputParser.java
> +    public boolean isOption(String key) {
сделано

2024-04-03 14:54 UTC, DavidGelmanSerg commented on SimpleCalculator/src/InputParser.java
> +        Options = options;
сделано

2024-04-11 17:17 UTC, DavidGelmanSerg commented on SimpleCalculator/src/output/streams/FileStream.java
> +            System.out.println("Файл, который вы указали, не существует!");
Исключения этого класса проверяемые. Я не понимаю, как их правильно обрабатывать, потому что без их перехвата нельзя написать вызов метода записи в файл.
Если я беру PrinterWriter, то должен обработать FileNotFoundException, А если FileWriter, то IOException. Причем сразу после его возникновения, так как оно прерываемое.
Учитывая, что я реализую интерфейс, который не выбрасывает подобные исключения.
Я могу, допустим в интерфейсе сделать default метод и выбрасывать это исключение там.
Вопрос заключается в том, могу ли я это сделать? И самое главное  будет ли это правильно?

2024-04-14 16:04 UTC, DavidGelmanSerg commented on SimpleCalculator/src/operations/Division.java
> +    public double compute(double[] args) {
Сделано

2024-04-14 16:04 UTC, DavidGelmanSerg commented on SimpleCalculator/src/operations/Operation.java
> +    public Operation() {
сделано

2024-04-14 16:04 UTC, DavidGelmanSerg commented on SimpleCalculator/src/operations/Multiplication.java
> +    public double compute(double[] args) {
удалено

2024-04-14 16:04 UTC, DavidGelmanSerg commented on SimpleCalculator/src/operations/Multiplication.java
> +public class Multiplication extends Operation {
удалено

2024-04-14 16:05 UTC, DavidGelmanSerg commented on SimpleCalculator/src/operations/Operation.java
> +            default -> new Division();
Сделано

2024-04-14 16:07 UTC, DavidGelmanSerg commented on SimpleCalculator/src/Main.java
> +            System.exit(0);
сделано

2024-04-14 16:07 UTC, DavidGelmanSerg commented on SimpleCalculator/src/Calculator.java
> +            Pattern pattern = Pattern.compile("-?\\d+");
удалено

2024-04-14 16:11 UTC, DavidGelmanSerg commented on SimpleCalculator/src/Calculator.java
> +            throw new ExpressionNotValidException("Выражение введено неверно. Попробуйте ввести его в формате: число [-+*/:] число");
Сделано

2024-04-14 16:12 UTC, DavidGelmanSerg commented on SimpleCalculator/src/output/streams/IStream.java
> +public interface IStream {
Сделано

2024-04-14 16:15 UTC, DavidGelmanSerg commented on SimpleCalculator/src/output/Output.java
> +    private IStream outputStream;
Вообще, это уже удалено, но делать setOutputStream в данном случае не нужно, чтобы не было возможности изменять точку вывода. Это может привести к недоразумениям, вроде тех, когда нечаянно присвоил не там не тот поток для вывода и вывод вдруг стал происходит не туда. Тогда пришлось просматривать весь код на проверку тех мест, где поток задается явным образом через метод.

2024-04-14 16:15 UTC, DavidGelmanSerg commented on SimpleCalculator/src/output/Output.java
> +public class Output {
сделано

2024-04-14 16:15 UTC, DavidGelmanSerg commented on SimpleCalculator/src/input/parser/InputParser.java
> +    public Operation getExpression() throws InvalidExpressionException {
Сделано

2024-04-14 16:16 UTC, DavidGelmanSerg commented on SimpleCalculator/src/input/parser/InputParser.java
> +            System.out.println("Введите выражение:");
Сделано

2024-04-14 16:16 UTC, DavidGelmanSerg commented on SimpleCalculator/src/input/parser/InputParser.java
> +        return (value == null) ? "" : value;
сделано

2024-04-14 16:17 UTC, DavidGelmanSerg commented on SimpleCalculator/src/input/analyzer/exceptions/InvalidExpressionException.java
> +        super("");
сделано

2024-04-14 16:17 UTC, DavidGelmanSerg commented on SimpleCalculator/src/input/analyzer/exceptions/InvalidExpressionException.java
> +public class InvalidExpressionException extends Exception{
сделано

2024-04-14 16:18 UTC, DavidGelmanSerg commented on SimpleCalculator/src/calculator/operations/Sum.java
> +    public void setOperand1(double operand) {
сделано

2024-04-14 16:18 UTC, DavidGelmanSerg commented on SimpleCalculator/src/calculator/exceptions/DivisionByZeroException.java
> +    public DivisionByZeroException() {
сделано

2024-04-14 16:19 UTC, DavidGelmanSerg commented on SimpleCalculator/src/calculator/Calculator.java
> +    private Operation operation;
сделано

2024-04-14 16:19 UTC, DavidGelmanSerg commented on SimpleCalculator/src/Main.java
> +            System.out.println("Отсутствует значение для аргумента: " + invalidArg.getMessage());
Сделано

2024-05-06 03:34 UTC, Yuksovich commented on SimpleCalculator/src/Main.java
> +               Вот в этом моменте я тоже совсем не понял, как поступать правильно. Мне нужно в зависимости от ключа
тут стоит посмотреть паттерн фабрика. Вообще мэин должен оперировать абстракциями по возможности. Т.е. есть интерфейс OutputPrinter и мэин не знает, какая у него реализация. Т.е. фабрика исходя из аргументов решает, какая будет реализация ConsolePrinter или FilePrinter или вообще UI и здесь уже их упоминания отсутствуют. Если тебе требуется новый вывод - ты создаешь новую имплементацию OutputPrinter и добавляешь ее в фабрику. Мэин при этом вообще не меняется

2024-05-06 03:45 UTC, Yuksovich commented on SimpleCalculator/src/expression/ExpressionParser.java
> +            if (NumberUtils.isNumber(token) || SEPARATORS.contains(token)) {
когда используешь contains - лучше всего использовать Set. В данном случае программа будет перебирать всю строку на совпадения, в случае сета - механизм намного быстрее. В данном случае это конечно не очень принципиально, но в любом случае подход будет более правильным, в том числе с точки зрения ООП как оперирования объектами. Плюс ко всему, у тебя набор операндов встречается тут как строка, выше в виде switch и там и там по сути дублируются одни и те же символы. Их стоит вынести в константы, т.е. класс с константами, у которых говорящие понятные названия и брать их от туда

2024-05-06 03:49 UTC, Yuksovich commented on SimpleCalculator/src/expression/ExpressionParser.java
> +        Stack<String> opertationStack = new Stack<>();
Stack - уже никто не использует, он по сути является устаревшим. В описании даже написано использовать Deque. Deque - это двусторонняя очередь, т.е. она одновременно имеет операции очереди - FIFO и операции стэка - LIFO. Deque (по русски называют "дек") это интерфейс, у него есть ряд реализаций например ArrayDeque или LinkedList

2024-05-06 03:50 UTC, Yuksovich commented on SimpleCalculator/src/expression/NumberUtils.java
> +public class NumberUtils {
для утилитарного класса рекомендуется создавать приватный конструктор, пустой. Просто, чтобы никто не догадался создавать экземпляр этого класса

2024-05-06 03:53 UTC, Yuksovich commented on SimpleCalculator/src/output/printers/FilePrinter.java
> +            ConsolePrinter printer = new ConsolePrinter();
этого тут точно быть не должно

2024-05-06 03:54 UTC, Yuksovich commented on SimpleCalculator/src/output/printers/FilePrinter.java
> +            //Я не понимаю, как правильно обрабатывать подобные исключения в случае реализации интерфейсов.
вообще в таких случаях можно просто перебросить исключение завернув его в непроверяемое. Заодно можно залогировать. Но до логгеров мы пока не добрались, поэтому об этом можно немного позже. Хотя можешь почитать про логгеры и посмотреть, как их использовать

2024-05-06 03:55 UTC, Yuksovich commented on SimpleCalculator/SimpleCalculator.iml
этого файла так же не должно быть в проекте.

2024-05-10 06:23 UTC, DavidGelmanSerg commented on SimpleCalculator/src/expression/ExpressionParser.java
> +        Stack<String> opertationStack = new Stack<>();
Исправил

2024-05-10 06:24 UTC, DavidGelmanSerg commented on SimpleCalculator/src/expression/NumberUtils.java
> +public class NumberUtils {
Исправлено

2024-05-10 08:23 UTC, DavidGelmanSerg commented on SimpleCalculator/src/expression/ExpressionParser.java
> +            if (NumberUtils.isNumber(token) || SEPARATORS.contains(token)) {
Сделано

2024-05-12 13:27 UTC, DavidGelmanSerg commented on SimpleCalculator/SimpleCalculator.iml
сделано

2024-05-12 13:27 UTC, DavidGelmanSerg commented on SimpleCalculator/src/output/printers/FilePrinter.java
> +            //Я не понимаю, как правильно обрабатывать подобные исключения в случае реализации интерфейсов.
сделано

2024-05-12 13:28 UTC, DavidGelmanSerg commented on SimpleCalculator/src/output/printers/FilePrinter.java
> +            ConsolePrinter printer = new ConsolePrinter();
удалено. Заменено на выброс непроверяемого исключения.

2024-05-12 13:28 UTC, DavidGelmanSerg commented on SimpleCalculator/src/Main.java
> +               Вот в этом моменте я тоже совсем не понял, как поступать правильно. Мне нужно в зависимости от ключа
сделано

2024-05-14 10:48 UTC, Yuksovich commented on SimpleCalculator/src/expression/Operations.java
> +    public static HashSet<String> asSet() {
В методах не затачивайся на реализацию. Используй просто `Set<String>`. Тебе важно знать, что это просто Set

2024-05-14 10:48 UTC, Yuksovich commented on SimpleCalculator/src/expression/Operations.java
> +        return operationSet;
здесь вообще можно написать `return Set.of(SuM, SUBSTRACTION, MULTIPLICATION, DIVISION)`

2024-05-14 10:48 UTC, Yuksovich commented on SimpleCalculator/src/output/printers/ConsolePrinter.java
> +    PrintStream out;
почему не private final? И старайся соблюдать отступы, чтобы в куче все не было

2024-05-14 10:48 UTC, Yuksovich commented on SimpleCalculator/src/output/printers/ConsolePrinter.java
> +    {
скобки так в C# ставят, в Java так не принято

2024-05-14 10:48 UTC, Yuksovich commented on SimpleCalculator/src/output/printers/ConsolePrinter.java
> +    }
много где форматирование кривое. Не забывай Ctrl+Alt+L. Можно даже в меню коммита в идее поставить галочку reformat code и optimize imports, чтобы перед коммитом идея автоматом причесывала код, если ты забыл это сделать

2024-05-14 10:48 UTC, Yuksovich commented on SimpleCalculator/src/ui/AbstractKeyHandler.java
> +public class AbstractKeyHandler implements KeyListener{
чтобы подобного не создавать - есть KeyAdapter

2024-05-14 10:48 UTC, Yuksovich commented on SimpleCalculator/src/ui/CalculatorFrame.java
> +            int code = event.getKeyCode();
лучше переменную объявлять ближе к месту использования

2024-05-14 10:48 UTC, Yuksovich commented on SimpleCalculator/src/ui/CalculatorFrame.java
> +                case 8: {
что это за магические коды? для того чтобы было понятно, что означают эти 8, 10, 61 - делают константы с говорящими названиями. Потому что я вот не знаю, что это за коды, да и ты не вспомнишь через пару месяцев. 
Возможно, кстати, что для этих кодов где то в SDK уже заведены константы

2024-05-14 10:48 UTC, Yuksovich commented on SimpleCalculator/src/ui/CalculatorFrame.java
> +import output.printers.PrinterFactory;
не должно быть тут этих ссылок. Т.е.  UI не должен ничего знать про логику. Как например кнопка JButton ничего не знает, где и как ее будут использовать, поэтому у нее есть Listener'ы, которые ты сам добавляешь.
Этот паттерн называется Слушатель или Наблюдатель или Listener или Observer - всегда, когда видишь в коде слово Listener или Observer - можешь считать, что используется данный паттерн. Он очень распространен в самых разных областях и очень полезен. Прочитай повнимательнее о нем и отвяжи UI от логики при помощи данного паттерна.

2024-05-14 10:48 UTC, Yuksovich commented on SimpleCalculator/src/ui/CalculatorFrame.java
> +        public void actionPerformed(ActionEvent e) {
это можно сделать через анонимный класс

2024-05-14 10:48 UTC, Yuksovich commented on SimpleCalculator/src/Main.java
> +        EventQueue.invokeLater(() -> {
ну теперь весь каклькулятор только с UI получается. А как же остальные способы? Хотелось бы, чтобы мэин оставался прежним, чтобы можно было выбрать, через что будет работать программа

2024-05-14 11:05 UTC, Yuksovich commented on SimpleCalculator/src/ui/CalculatorFrame.java
> +            switch (code) {
какая версия Java и SDK у тебя используется? идея предлагает enhanced форму использовать для свитча - такие предложения не стоит игнорировать

2024-05-14 11:05 UTC, Yuksovich commented on SimpleCalculator/src/expression/exceptions/EmptyExpressionException.java
> +package expression.exceptions;
у тебя несколько пакетов с эксепшенами - вынеси их в один

2024-05-14 11:05 UTC, Yuksovich commented on SimpleCalculator/src/Main.java
> +    public static void main(String[] args) {
добивайся того, чтобы в окне редактора была зеленая галочка в правом верхнем углу - это значит, что идея не видит проблем в твоем коде в статическом анализаторе. Если есть таковые - исправляй их. В том числе опечатки

2024-05-17 06:45 UTC, DavidGelmanSerg commented on SimpleCalculator/src/expression/Operations.java
> +    public static HashSet<String> asSet() {
сделано

2024-05-17 06:46 UTC, DavidGelmanSerg commented on SimpleCalculator/src/expression/Operations.java
> +        return operationSet;
сделано

2024-05-17 06:48 UTC, DavidGelmanSerg commented on SimpleCalculator/src/output/printers/ConsolePrinter.java
> +    PrintStream out;
Сделано

2024-05-17 06:48 UTC, DavidGelmanSerg commented on SimpleCalculator/src/output/printers/ConsolePrinter.java
> +    {
сделано

2024-05-17 06:51 UTC, DavidGelmanSerg commented on SimpleCalculator/src/ui/AbstractKeyHandler.java
> +public class AbstractKeyHandler implements KeyListener{
Сделано

2024-05-17 07:21 UTC, DavidGelmanSerg commented on SimpleCalculator/src/ui/CalculatorFrame.java
> +            switch (code) {
У меня используется Java 17.0.2 и SDK 17. Таких рекомендаций от Idea не было. Но я это запомню. Исправлено

2024-05-17 07:22 UTC, DavidGelmanSerg commented on SimpleCalculator/src/ui/CalculatorFrame.java
> +                case 8: {
Сделано

2024-05-28 05:10 UTC, DavidGelmanSerg commented on SimpleCalculator/src/expression/exceptions/EmptyExpressionException.java
> +package expression.exceptions;
У меня была подобная мысль.
Потом я подумал, что раз это служебные классы, которые потом можно переиспользовать, то не лучше было бы, чтобы каждый такой пакет служебных классов имел еще и свой подпакет с эксепшенами? Или эксепшены располагаются точно также, как и другие классы - в одном пакете?

2024-06-03 04:00 UTC, DavidGelmanSerg commented on SimpleCalculator/src/Main.java
> +    public static void main(String[] args) {
Сделан

2024-06-03 04:01 UTC, DavidGelmanSerg commented on SimpleCalculator/src/Main.java
> +        EventQueue.invokeLater(() -> {
Сделано

2024-06-03 04:01 UTC, DavidGelmanSerg commented on SimpleCalculator/src/ui/CalculatorFrame.java
> +        public void actionPerformed(ActionEvent e) {
Сделано

2024-06-03 04:01 UTC, DavidGelmanSerg commented on SimpleCalculator/src/ui/CalculatorFrame.java
> +import output.printers.PrinterFactory;
Сделано. Все логика перенесена в Main

2024-06-03 04:02 UTC, DavidGelmanSerg commented on SimpleCalculator/src/ui/CalculatorFrame.java
> +            int code = event.getKeyCode();
Сделано

2024-07-07 13:54 UTC, merged